[package]
name = "napi_sandbox"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["dylib"]

[dependencies]
futures = "0.3.30"
neon = { version = "=1.1.0-alpha.0", features = ["futures"] }
once_cell = "1.19.0"
tokio = { version = "1.38.0", features = ["full"] }
